### PR TITLE
fix(android): prevent ProGuard from blocking access to `mBundleLoader`

### LINKED ISSUE #105: Scenario crash when UPDATE OR ROLLBACK to the on Android
when update or rollback is done in android application, the application crashes. The process is completed successfully, the update is done, but the application crashes when it will reload. 
it makes no difference whether it is force or not. 
No problem on iOS. 

Device samsung s24 ultra
react native : 0.76.5
android version 14

logcat logs 

 java.lang.RuntimeException: Could not invoke HotUpdater.updateBundle
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:188)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:19)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(Unknown Source:35)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.b(Unknown Source:0)
                                                                                                    	at com.facebook.react.bridge.queue.b.run(Unknown Source:2)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:150)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:19) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(Unknown Source:35) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.b(Unknown Source:0) 
                                                                                                    	at com.facebook.react.bridge.queue.b.run(Unknown Source:2) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.IllegalAccessException: Could not setJSBundle
                                                                                                    	at Tc.d.d(Unknown Source:84)
                                                                                                    	at com.hotupdater.a$a.i(Unknown Source:47)
                                                                                                    	at com.hotupdater.a$a.k(Unknown Source:321)
                                                                                                    	at com.hotupdater.HotUpdaterModule.updateBundle(Unknown Source:19)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:150) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:19) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(Unknown Source:35) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.b(Unknown Source:0) 
                                                                                                    	at com.facebook.react.bridge.queue.b.run(Unknown Source:2) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

### PR DESCRIPTION
**Pull request by mstfmedeni**
No field mBundleLoader in class Lcom/facebook/react/ issue fixed

Closed #105

### CODE REVIEW

File: packages/react-native/android/src/oldarch/ReactIntegrationManager.kt [hunk 1]
```diff
@@ -16,17 +15,13 @@ class ReactIntegrationManager(
         try {
             val instanceManager = application.reactNativeHost.reactInstanceManager
             val bundleLoader: JSBundleLoader? = this.getJSBundlerLoader(bundleURL)
-            val bundleLoaderField: Field =
-                instanceManager::class.java.getDeclaredField("mBundleLoader")
+            val bundleLoaderField = instanceManager.javaClass.getDeclaredField("g")
```
Comment (gronxb) [inline packages/react-native/android/src/oldarch/ReactIntegrationManager.kt:18]: What does the “g” field mean? Originally, mBundleLoader existed in ReactHost, but it seems to be missing in your implementation. I’d like to know the background of why you decided to use “g” instead.

Comment (mstfmedeni) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt:18]: We directly target the g field because we see from the logs that this field is of type JSBundleLoader:

CopyField: g - Type: class com.facebook.react.bridge.JSBundleLoader

We access the g field using Reflection and set the new bundle loader directly to this field.

[find class.txt](https://github.com/user-attachments/files/18813466/find.class.txt)

Comment (gronxb) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt:18]: https://github.com/microsoft/react-native-code-push/blob/6015386f22c61417cd2b2ae2860a9ad69c37f643/android/app/proguard-rules.pro#L4


I believe the original field name exists, but it was renamed to g during the ProGuard obfuscation process. Instead of modifying the original code, we can declare it this way to handle ProGuard exceptions. Could we apply this to the PR and see if it resolves the issue?

Comment (gronxb) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt:18]: Can we revert the `ReactIntegrationManager.kt` file and apply the two files (ProGuard) to the same hot-updater path in

[hot-updater repository](https://github.com/gronxb/hot-updater/tree/main/packages/react-native/android)

and update the PR?

Thanks to your debugging help, I feel like we’ve found a clue!

Comment (mstfmedeni) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt]: yeah, you're right. if I didn't make a mistake and it didn't work from cache or something, everything seems fine. pushed the changes.

Comment (mstfmedeni) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt]: I also checked #106  PR at the same time. it works better, can you check if there is no problem

Comment (gronxb) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt]: Yes, yes. Lastly, did applying ProGuard solve your issue?

**Review by gronxb — APPROVED** [review]

File: packages/react-native/android/src/oldarch/ReactIntegrationManager.kt (hunk 1 above)
Comment (gronxb) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt]: @mstfmedeni  If your issue is resolved after applying ProGuard, I will merge the PR.

Comment (mstfmedeni) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt]: yes my problem has been solved. if there is anything different I will let you know. thank you for your support

Comment (gronxb) [reply packages/react-native/android/src/oldarch/ReactIntegrationManager.kt]: Thank you for your hard work. Thanks to you, debugging went smoothly, and I found a clue. I appreciate your contribution.

File: packages/react-native/android/proguard-rules.pro [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+#   public *;
+#}
+
+# Invoked via reflection, when setting js bundle.
+-keepclassmembers class com.facebook.react.ReactInstanceManager {
+    private final ** mBundleLoader;
+}
+
+# Can't find referenced class org.bouncycastle.**
+-dontwarn com.nimbusds.jose.**
```
Comment (gronxb) [inline packages/react-native/android/proguard-rules.pro:25]:
```suggestion
```

**Comment by gronxb** [comment]
Released in 0.8.0.
