### PR TITLE
fix(firebase): index default

### LINKED ISSUE #407: Firebase Cannot read properties of undefined (reading 'concat'). Error while creating cloud function
### Precheck

- [x] Infrastructure may have changed. Did you retry `hot-updater init`?
- [x] Is your Node version v20 or higher?
- [x] Are you aware that the update will only work properly if you `hot-updater deploy` after building the native app?

### Name, Version of hot-updater

0.18.5

### Version of react-native

0.74.5

### Platforms

Android, iOS

### Architecture

New Architecture(Fabric)

### What provider are you seeing the problem on? (multiple)

Firebase

### Expo App

- [ ] I am using Expo
- [ ] Project is managed with Expo [CNG](https://docs.expo.dev/workflow/continuous-native-generation/)(android, ios directories are included in `.gitignore`)

### Bundler

metro

### What happened?

Hi,

While selecting a region for my cloud function, an error about Firestore indexes is thrown.

Here is the [location](https://github.com/gronxb/hot-updater/blob/main/plugins/firebase/iac/index.ts) where the error happening.

We are trying to get actual indexes like this :
`originalIndexes = originalStdout ?? []`

While if not found it should be this (at least for my case)
`{ indexes: [], fieldOverrides: [] }`

Hence the error `Cannot read properties of undefined (reading 'concat')`

### Relevant log output

```shell
◇  Select Region
◇  Using new functions in region: europe-west1
file:///Users/damien/Work/project/node_modules/@hot-updater/firebase/dist/iac/index.js:8191
	const mergedIndexes = originalIndexes.indexes.concat(newIndexes.indexes);
	                                              ^

TypeError: Cannot read properties of undefined (reading 'concat')
    at mergeIndexes (file:///Users/damien/Work/project/node_modules/@hot-updater/firebase/dist/iac/index.js:8191:48)
    at deployFirestore (file:///Users/damien/Work/project/node_modules/@hot-updater/firebase/dist/iac/index.js:8209:24)
    at async Module.runInit (file:///Users/damien/Work/project/node_modules/@hot-updater/firebase/dist/iac/index.js:8354:2)
    at async Command.init (file:///Users/damien/Work/project/node_modules/hot-updater/dist/index.js:21019:4)

Node.js v20.12.0
```

### Reproducible Sample Repository

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jingjing2222**
## Before
There is not default value of fieldoverrides.
It occurred concat error

## after 

```typescript
originalIndexes = originalStdout ?? { indexes: [], fieldOverrides: [] };
```

and add exact type for index
https://firebase.google.com/docs/reference/firestore/indexes?hl=ko

closed #407

### CODE REVIEW

File: plugins/firebase/iac/index.ts [hunk 1]
```diff
@@ -77,8 +77,27 @@ interface FirebaseFunction {
...
+  queryScope: "COLLECTION" | "COLLECTION_GROUP";
+  fields: Array<{
+    fieldPath: string;
+    order?: "ASCENDING" | "DESCENDING";
+    arrayConfig?: "CONTAINS";
+    vectorConfig?: {
+      dimension: number;
+      flat: Record<string, never>;
+    };
+  }>;
```
Comment (gronxb) [inline plugins/firebase/iac/index.ts]:
```suggestion
  fields: {
    fieldPath: string;
    order?: "ASCENDING" | "DESCENDING";
    arrayConfig?: "CONTAINS";
    vectorConfig?: {
      dimension: number;
      flat: Record<string, never>;
    };
  }[];
```
